# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-18 11:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='requests',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
